/*! ver:1449045431 Copyright 2015 Baidu Inc. All Rights Reserved. */;(function(){var m=!0,o=null,r=!1;
window.BAIDU_DUP_define&&window.BAIDU_DUP_define("clb/monitor1449045431",[],function(){return{sendLog:function(f){if(f=f.data&&f.data.monitorUrl){var c=new Image,d="log"+ +new Date;window[d]=c;c.onload=c.onerror=c.onabort=function(){c.onload=c.onerror=c.onabort=o;try{delete window[d]}catch(b){window[d]=void 0}};c.src=f}},expLog:function(f){var c=new Image,d="BAIDU_DUP_log_"+Math.floor(2147483648*Math.random()).toString(36);window[d]=c;c.onload=c.onerror=c.onabort=function(){c.onload=c.onerror=c.onabort=o;c=
window[d]=o};c.src=f}}});
window.BAIDU_DUP_define&&window.BAIDU_DUP_define("clb/template1449045431",[],function(){function f(c){var b={'"':"&quot;",">":"&gt;","<":"&lt;","&":"&amp;"};return c.replace(/[\"<>\&]/g,function(c){return b[c]})}var c=/\{(\w+)\:(\w+)\}/g;return{a:function(d,b){return d.replace(c,function(c,a,h){c=b[a];switch(h){case "number":c=+c||0;break;case "boolean":c=!!c;break;case "html":c=f(c)}return c})}}});
window.BAIDU_DUP_define&&window.BAIDU_DUP_define("clb/material1449045431",["clb/template1449045431"],function(f){function c(b,e,a){if("string"===typeof b)return b;if(!b.type)return"";var h=d[b.type];return h?(b="string"===typeof h?f.a(h,b):h(b,e),a?b:"<!DOCTYPE html><body>"+b):""}var d={text:function(b){var e='<span style="word-wrap:break-word;"><a href="{clickUrl:string}" target="{target:string}" style="font-size:{size:number}{unit:string};color:{defaultColor:string};font-weight:{defaultBold:string};font-style:{defaultItalic:string};text-decoration:{defaultUnderline:string};"{events}>{text:string}</a></span>',a=
/\{events\}/;if(1===b.version)e=e.replace(a,"");else if(2===b.version)for(var e=e.replace(a," onmouseover=\"this.style.color='{hoverColor:string}';this.style.fontWeight='{hoverBold:string}';this.style.fontStyle='{hoverItalic:string}';this.style.textDecoration='{hoverUnderline:string}';\" onmouseout=\"this.style.color='{defaultColor:string}';this.style.fontWeight='{defaultBold:string}';this.style.fontStyle='{defaultItalic:string}';this.style.textDecoration='{defaultUnderline:string}';\""),a=["default",
"hover"],h=0;h<a.length;h++){var c=a[h],d=c+"Color",j=c+"Bold",k=c+"Italic",c=c+"Underline";b[d]="#"+b[d];b[j]=b[j]?"bold":"normal";b[k]=b[k]?"italic":"normal";b[c]=b[c]?"underline":"none"}return f.a(e,b)},image:'<a href="{clickUrl:string}" target="{target:string}"><img src="{src:string}" title="{title:html}" alt="{title:html}" border="0" height="{height:number}" width="{width:number}" /></a>',flash:function(b){b.file=b.hasLink?"cflash":"flash";b.imageClickUrl=b.clickUrl;b.hasLink||(b.clickUrl="");
return f.a('<script>var BD = BD || {};BD.MC = BD.MC || {};BD.MC.ADFlash = BD.MC.ADFlash || {};BD.MC.ADImg = BD.MC.ADImg || {};BD.MC.ADFlash.w = {width:number};BD.MC.ADFlash.h = {height:number};BD.MC.ADFlash.mu = "{src:string}";BD.MC.ADFlash.cu = "{clickUrl:string}";BD.MC.ADFlash.wm = {wmode:number};BD.MC.ADFlash.ct = "{clickTag:string}";BD.MC.ADImg.w = {imageWidth:number};BD.MC.ADImg.h = {imageHeight:number};BD.MC.ADImg.mu = "{imageSrc:string}";BD.MC.ADImg.cu = "{imageClickUrl:string}";BD.MC.ADImg.tw = "{target:string}";BD.MC.ADImg.flag = {backupImage:number};<\/script><script src ="http://cbjs.baidu.com/js/{file:string}.js"><\/script>',
b)},rich:function(b){return b.content},slide:function(b,e){for(var a=[],h=b.materials,d=0;d<h.length;d++){var i=h[d];"string"!==typeof i&&(i=c(i,e,m));a.push(i)}b.html="<div>"+a.join("</div><div>")+"</div>";b.width=e.width;b.height=e.height;return f.a('<div id="bd_ec_clb_asp" style="width:{width:number}px;height:{height:number}px;overflow:hidden;">{html:string}</div><script>(function(){var d = document;function G(id) { return d.getElementById(id); };var container = G("bd_ec_clb_asp");var pages = container.childNodes;var pl = 0;for (var i = 0; i < pages.length; i++) {if (pages[i].nodeType === 1) {pl++;}}var cp = 0;function showPage(pn) { pages[pn].style.display = ""; };function hidePages() {for (var i = 0; i < pl; i++) {pages[i].style.display = "none";}};function roll() {hidePages();showPage(cp);cp == (pages.length - 1) ? cp = 0 : cp++;};var autoRoll;function setRoll() { autoRoll = window.setInterval(function() { roll(); }, {interval:number});};roll();setRoll();container.onmouseover = function() { window.clearInterval(autoRoll); };container.onmouseout = function() {setRoll(); };})();<\/script>',
b)}};return{a:c}});
window.BAIDU_DUP_define&&window.BAIDU_DUP_define("clb/frame1449045431",["api"],function(f){function c(){var b=document.createElement("iframe"),a=r;b.src="about:blank";document.body.insertBefore(b,document.body.firstChild);try{a=!b.contentWindow.document}catch(h){a=m}document.body.removeChild(b);c=function(){return a};return a}function d(){var b=navigator.userAgent,a=b&&b.match(/iphone.*micromessenger/i)?m:r;d=function(){return a};return a}function b(){return c()?f.getConfig("domainPolicyFileUrl")||"/domain-policy.htm":
d()?f.getConfig("blankPolicyFileUrl")||"/blank-policy.htm":"about:blank"}f.defineOnce("BAIDU_DUP_CLB_renderFrame",function(e){var a=document.getElementById("baidu_clb_slot_iframe_"+e),h=f.getSlots(e);if(h)if(c()&&a.getAttribute("src",2)!==b())a.src=b();else if(h&&!h.status.finish)try{f.setStatus(e,"finish");var d=f.getInfo("#"+e).html;0>d.indexOf("<body>")&&(d="<!DOCTYPE html><body>"+d);var i=a.contentWindow.document;i.open("text/html","replace");i.write(d);i.close();i.body&&(i.body.style.backgroundColor=
"transparent")}catch(j){f.addErrorItem(e,"PermissionDenied")}});return{o:function(){return c()},l:b,k:function(e,a){var c;c=a.id;c='<iframe id="baidu_clb_slot_iframe_'+c+'" src="'+b()+'" onload="BAIDU_DUP_CLB_renderFrame(\''+c+'\')" width="'+a.width+'" height="'+a.height+'" vspace="0" hspace="0" allowTransparency="true" scrolling="no" marginWidth="0" marginHeight="0" frameborder="0" style="border:0; vertical-align:bottom; margin:0; display:block;"></iframe>';e.innerHTML=c}}});
window.BAIDU_DUP_define&&window.BAIDU_DUP_define("clb/logService1449045431",["api","clb/monitor1449045431"],function(f,c){var d=r;return{i:function(b){!d&&64!==b.slotType&&(d=m,f.bind(window,"load",function(){window.BAIDU_DUP_require(["clb/detect"],function(){},m)}))},g:function(b){var e=f.getSlots(b.id);e.status.expid&&c.expLog("http://cbjslog.baidu.com/log?"+["id="+b.id,"&slotType="+b.j||b._stype,"&mlt="+b.h||b._isMlt,"&exp="+e.status.expid,"&ltu="+e.status.ltu,"&from=dup","&tm="+(new Date).getTime()].join(""))}}});
window.BAIDU_DUP_define&&window.BAIDU_DUP_define("clb/fixed7o",["api","clb/monitor1449045431","clb/material1449045431","clb/frame1449045431","clb/logService1449045431"],function(f,c,d,b,e){return{render:function(a,h){a={id:a.id,data:a._html,m:a._fxp,j:a._stype,h:a._isMlt,width:a._w,height:a._h};e.i(a);c.sendLog(a);e.g(a);if(!a.data&&!a.m)f.setStatus(a.id,"finish");else{if(a.h&&"sync"===f.getFillType(a.id)){var p="string"===typeof a.data?a.data:a.data.content;if(p){f.setStatus(a.id,"finish");document.write(p);return}}if(!h)return o;var p=
document.getElementById(h),i=d.a(a.data,a,m);f.putInfo("#"+a.id,{html:i});b.k(p,a)}},validate:function(a){var b=a._stype,a=a._isMlt;return 0!==b&&3!==b&&64!==b||0!==a&&1!==a&&a!==r?r:m}}});
})();
window.BAIDU_DUP_define&&window.BAIDU_DUP_define("clb/detect",["api"],function(g){function e(a){a.url="";a.host=window.location.hostname;a.from="DUP";g.sendLog({data:a,a:"now"})}try{setTimeout(function(){var a=g.getSlots(),c;for(c in a){var b=a[c],h=b.status;if(h.render){for(var d=b.errors,i=!1,f=0;f<d.length;f++)if("PermissionDenied"===d[f]){i=!0;break}d=b.response.data&&b.response.data._html;if(i)e({type:"renderFail",id:c,error:"PermissionDenied",empty:!!d});else if(h.finish){if(1!==b.response.data._isMlt&&
(b=document.getElementById("baidu_clb_slot_iframe_"+c)))try{var j=b.contentWindow.document.body;(!j||!j.firstChild)&&e({type:"renderEmpty",id:c})}catch(k){}}else e({type:"renderFail",id:c,error:"NotFilled",empty:!!d})}}},0)}catch(k){}});