var OX_cf51fd2e = '';
OX_cf51fd2e += "<"+"!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n";
OX_cf51fd2e += "<"+"html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\">\n";
OX_cf51fd2e += "<"+"head>\n";
OX_cf51fd2e += "<"+"meta http-equiv=\"Content-Type\" content=\"text/html;charset=UTF-8\">\n";
OX_cf51fd2e += "<"+"style>html,body{ margin:0; padding:0;border:0}<"+"/style>\n";
OX_cf51fd2e += "<"+"title>1649<"+"/title>\n";
OX_cf51fd2e += "<"+"/head>\n";
OX_cf51fd2e += "<"+"body>\n";
OX_cf51fd2e += "<"+"iframe src=\"http://x.jd.com/exsites?spread_type=2&ad_ids=1649:5&location_info=0&adflag=0\" width=\"760\" height=\"90\" frameborder=\"0\" style=\"border:0px\" srcolling=\"no\"><"+"/iframe>\n";
OX_cf51fd2e += "<"+"/body>\n";
OX_cf51fd2e += "<"+"/html><"+"div id=\'beacon_e33816138f\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'//gg2.51cto.com/www/delivery/lg.php?bannerid=2624&amp;campaignid=589&amp;zoneid=176&amp;loc=1&amp;referer=http%3A%2F%2Fother.51cto.com%2Fad%2Fart%2Ftonglan%2F2.htm&amp;cb=e33816138f\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
document.write(OX_cf51fd2e);
